import type { Metadata } from "next";
import { IM_Fell_English, La_Belle_Aurore, Sorts_Mill_Goudy } from "next/font/google";
import "./globals.css";

const mainFont = IM_Fell_English({
  weight: ['400'],
  subsets: ["latin"],
  variable: '--font-main',
})

const accentFont = La_Belle_Aurore({
  weight: ['400'],
  subsets: ["latin"],
  variable: '--font-accent',
})

const bodyFont = Sorts_Mill_Goudy({
  weight: ['400'],
  subsets: ["latin", "latin-ext"],
  variable: '--font-body',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ background: 'white' }}>
      <body className={`${mainFont.variable} ${bodyFont.variable} ${accentFont.variable}`}>{children}</body>
    </html>
  );
}
